apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: istio-system
  annotation:
    openshift.io/description: "Project where the Istio and Kiali projects are installed"
    openshift.io/display-name: "Istio System"
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: service-mesh-test
  annotation:
    openshift.io/description: "Service Mesh test project"
    openshift.io/display-name: "Service Mesh Test"
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system # This project needs to be created first!
spec:
  version: v2.3
  tracing:
    type: Jaeger
    sampling: 10000
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - service-mesh-test
