apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: catalog
    apiVersion: apps.openshift.io/v1
    subresource: scale
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
