apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalog-monitor
  labels:
    app: catalog
spec:
  selector:
    matchLabels:
      app: catalog
  endpoints:
  - port: web

